logging:
  entity_types:
    direct_link_entity: direct_link_entity
    node: node
    taxonomy_term: taxonomy_term
    user: user
    block_content: 0
    comment: 0
    contact_message: 0
    file: 0
    shortcut: 0
    menu_link_content: 0
_core:
  default_config_hash: wIs6Q7ndBaxmH2QphZXy8nJAmrgivttZYPJR1i_xJ7E
langcode: fr
