<?php

/**
 * @file
 * Contains direct_link_entity.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function direct_link_entity_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the direct_link_entity module.
    case 'help.page.direct_link_entity':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Create and edit direct link entities') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function direct_link_entity_theme() {
  return [
    'direct_link_entity' => [
      'render element' => 'children',
    ],
  ];
}
