version: "3.7"

services:
  postgres:
    image: postgres:11
    environment:
      POSTGRES_DB: $POSTGRES_NAME
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - ./sql/import:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'

  php:
    build:
      context: ./docker/php/
      args:
        - "VERSION=${PHP_VERSION}-${COMPOSER_VERSION}"
      dockerfile: Dockerfile
    environment:
      PHP_XDEBUG: 1
      PHP_XDEBUG_REMOTE_ENABLE: 1
      PHP_XDEBUG_REMOTE_PORT: 9000
      PHP_XDEBUG_REMOTE_CONNECT_BACK: 1
    env_file:
      - .env
    volumes:
      - ./:/var/www
      - ./:/srv
      - ~/.composer/:/home/.composer/
      - ./docker/php/php-mail.conf:/usr/local/etc/php/conf.d/mailconf.ini

  apache:
    image: wodby/apache:$APACHE_TAG
    depends_on:
      - php
    environment:
      APACHE_LOG_LEVEL: debug
      APACHE_BACKEND: php
      APACHE_VHOST_PRESET: php
      APACHE_DOCUMENT_ROOT:   /var/www/html
    volumes:
      - ./:/var/www
    ports:
      - '8080:80'

  node:
    build:
      context: ./docker/node
      args:
      - NODE_VERSION=${NODE_VERSION}
    working_dir: /srv
    env_file:
    - .env
    volumes:
    - ./:/srv/

  mail:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
